version = 0.1

[default.global.parameters]
stack_name = "trolling-time"
region = "us-east-1"

[default.deploy.parameters]
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "RiotApiKeySecretArn=\"CHANGE_ME\" SesSenderEmail=\"CHANGE_ME\" RecipientEmail=\"CHANGE_ME\""
